<?php

/**
 * Implements hook_field_info().
 */
function strategy_field_field_info() {
  $field_info['strategy_field'] = array(
    'label' => t('Strategy Field'),
    'description' => t('This field implements the Strategy pattern for dynamic processing at runtime.'),
    'default_widget' => 'strategy_field_widget',
    'default_formatter' => 'strategy_field_formatter',
  );
  return $field_info;
}

/**
 * Implements hook_field_widget_info().
 */
function strategy_field_field_widget_info() {
  return array(
    'strategy_field_widget' => array(
      'label' => t('Default Strategy Field'),
      'field types' => array('strategy_field'),
    ),
  );
}

/**
 * Implements hook_field_formatter_info().
 */
function strategy_field_field_formatter_info() {
  return array(
    'strategy_field_formatter' => array(
      'label' => t('Default Strategy Field'),
      'field types' => array('strategy_field'),
    ),
  );
}

/**
 * Implements hook_field_is_empty().
 */
function strategy_field_field_is_empty($item, $field) {
  return empty($item['class']);
}

/**
 * Implements hook_field_widget_form().
 */
function strategy_field_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
  $class_options = array();
  if (!$instance['required']) {
    $class_options[''] = t('None');
  }

  // Get Class options, for each class option, get form field
  // Get all strategy field base classes
  $strategy_type = $field['settings']['strategy_type'];
  $strategy_field_info = module_invoke_all('strategy_field_info');
  $classes = $strategy_field_info[$strategy_type];
  foreach ($classes as $class_name) {
    $class_options[$class_name] = $class_name::getLabel();
  }
  $field_name = $instance['field_name'];

  $element['class'] = array(
    '#type' => 'select',
    '#default_value' => empty($items[$delta]['class']) ? '' : $items[$delta]['class'],
    '#options' => $class_options,
    '#title' => $strategy_type,
    '#attributes' => array('class' => array('chosen-widget')),
    '#suffix' => '<br/>',      
  );

  $element['strategy_settings'] = array(
    '#type' => 'container',
  );

  foreach ($classes as $class_name) {
    $element['strategy_settings'][$class_name] = array(
      '#type' => 'fieldset',
      '#title' => '<strong>' . t(
        '%class_label settings',
        array('%class_label' => $class_name::getLabel())
      ) . '</strong>',
      '#description' => $class_name::getDescription(),
      '#states' => array(
        'visible' => array(
          ':input[name="' . $field_name . '[und][' . $delta . '][class]"]' => array('value' => $class_name)
        ),
      ),
    );
    $strategy_settings = array();
    if (!empty($items[$delta]['class']) && !strcmp($items[$delta]['class'], $class_name)) {
      $strategy_settings = $items[$delta]['strategy_settings'];
    }
    $class_object = new $class_name($strategy_settings);
    $element['strategy_settings'][$class_name] += $class_object->getForm();
  }
  
  return $element;
}

/**
 * Implements hook_field_settings_form().
 */
function strategy_field_field_settings_form($field, $instance, $has_data) {
  // Get all strategy field base classes
  $strategy_field_info = module_invoke_all('strategy_field_info');
  $settings = $field['settings'];

  $form = array();
  
  $form['strategy_type'] = array(
    '#type' => 'select',
    '#title' => t('Strategy Field Type'),
    '#default_value' => $settings['strategy_type'],
    '#required' => TRUE,
    '#description' => t('The type of Strategy.'),
    '#disabled' => $has_data,
    '#options' => array_combine(array_keys($strategy_field_info), array_keys($strategy_field_info)),
  );
  
  return $form;
}

/**
 * Implements hook_field_presave().
 */
function strategy_field_field_presave($entity_type, $entity, $field, $instance, $langcode, &$items) {
  foreach($items as $i => $item) {
    $strategy_settings = isset($item['strategy_settings'][$item['class']]) ? $item['strategy_settings'][$item['class']] : $item['strategy_settings'];
    $items[$i]['strategy_settings'] = serialize($strategy_settings);
  }
}

/**
 * Implements hook_field_load().
 */
function strategy_field_field_load($entity_type, $entities, $field, $instances, $langcode, &$items, $age) {
  foreach ($entities as $id => $entity) {
    foreach ($items[$id] as $delta => $item) {
      if (!is_array($item['strategy_settings'])) {
        $items[$id][$delta]['strategy_settings'] = unserialize($item['strategy_settings']);
        $items[$id][$delta]['object'] = new $item['class']($items[$id][$delta]['strategy_settings']);
      }
    }
  }
}


/**
 * Implements hook_field_formatter_view().
 */
function strategy_field_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();

  foreach ($items as $delta => $item) {
    if (!is_array($item['strategy_settings'])) {
      $item['strategy_settings'] = unserialize($item['strategy_settings']);
    }
    $item['display'] = $display;
    $element[$delta] = array(
      '#markup' => theme('strategy_field_formatter_default', $item),
    );
  }

  return $element;
}

/**
 * Implements hook_theme().
 */
function strategy_field_theme() {
  return array(
    'strategy_field_formatter_default' => array(
      'variables' => array(
        'class' => NULL,
        'values' => array(),
        'object' => NULL,
        'display' => NULL,
      ),
    ),
  );
}

/**
 * Formats a link.
 */
function theme_strategy_field_formatter_default($vars) {
  $formatted_strategy_field = $vars['object']->formatter($vars['display']);
  $output = array(
    '#theme' => 'html_tag',
    '#tag' => 'fieldset',
    '#value_prefix' => '<legend><strong>' . $vars['class']::getLabel() . '</strong></legend>',
    '#value' => drupal_render($formatted_strategy_field),
  );
  return drupal_render($output);
}

/**
 * Implements hook_field_field_validate().
 */
function strategy_field_field_validate($entity_type, $entity, $field, $instance, $langcode, $items, &$errors) {
  foreach ($items as $delta => $item) {
    // Check which class is set, then call validate for that class
    if (isset($item['class']) && !empty($item['class']) && isset($item['strategy_settings'][$item['class']])) {
      $strategy_obj = new $item['class']($item['strategy_settings'][$item['class']]);
      $validation_errors = $strategy_obj->validate();

      foreach ($validation_errors as $error_msg) {
        $errors[$field['field_name']][$langcode][$delta][] = array(
          'error' => 'strategy_field_error',
          'message' => t(
            '%title: @class: !error_msg',
            array(
              '%title' => $instance['label'],
              '@class' => $item['class'],
              '!error_msg' => $error_msg,
            )
          ),
        );
      }
    }
  }
}

/**
 * Implements hook_field_widget_error().
 */
function strategy_field_field_widget_error($element, $error, $form, &$form_state) {
  switch ($error['error']) {
    case 'strategy_field_error':
      form_error($element, $error['message']);
      break;
  }
}
